
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yashmor
 */
public class admin_stock extends javax.swing.JFrame {

    /**
     * Creates new form admin_stock
     */
    public admin_stock() {
        initComponents();
                setIconImage(new ImageIcon(getClass().getResource("icon.jpg")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        c2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daily Stocks,Creamstone ,Jaipur");
        setAutoRequestFocus(false);
        setFocusTraversalPolicyProvider(true);
        setMinimumSize(new java.awt.Dimension(1002, 633));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Daily Stock Update");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(122, 0, 465, 102);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Code");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 150, 80, 17);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 180, 80, 17);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Qty.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 210, 100, 17);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Price(in INR)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 120, 17);

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton1.setText("Print Daily Stock Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 540, 450, 25);

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton2.setText("Remove Item From Stock");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 300, 180, 25);

        jButton3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton3.setText("View Complete Stock");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 340, 450, 25);

        c1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FC21", "FC20", "MO10", "MO20", "SI01", "SI02", "SI03", "SI04", "SI05", "SI06", "SI07", "SI08", "SIR4", "SIR5", "SIR6", "SIR7", "FC15", "FC16", "FC304", "NC455", "NC23", "NCD4", "NC5", "CL23", "CL24", "FL3", "FL2", "FL1", "FL008", "CL28", "FRC10", "FL01", "NC09", "FC80", "NH43", "COC1", "OS453", "WW4", "COC2", "COC3", "NB34", "BB4", "TIN07", "CHO44", " ", " " }));
        getContentPane().add(c1);
        c1.setBounds(166, 142, 264, 23);

        t1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        getContentPane().add(t1);
        t1.setBounds(166, 176, 264, 23);

        t2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(166, 206, 264, 23);

        t3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        getContentPane().add(t3);
        t3.setBounds(166, 240, 264, 23);

        jTable1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Qty.", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 120, 452, 402);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)), "Check Particular Item Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei", 1, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Enter Code");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 30, 90, 20);

        l1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jPanel1.add(l1);
        l1.setBounds(20, 140, 450, 20);

        jButton4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton4.setText("Check Stock for Particular Item");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(100, 80, 210, 30);

        c2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FC21", "FC20", "MO10", "MO20", "SI01", "SI02", "SI03", "SI04", "SI05", "SI06", "SI07", "SI08", "SIR4", "SIR5", "SIR6", "SIR7", "FC15", "FC16", "FC304", "NC455", "NC23", "NCD4", "NC5", "CL23", "CL24", "FL3", "FL2", "FL1", "FL008", "CL28", "FRC10", "FL01", "NC09", "FC80", "NH43", "COC1", "OS453", "WW4", "COC2", "COC3", "NB34", "BB4", "TIN07", "CHO44", " ", " " }));
        jPanel1.add(c2);
        c2.setBounds(230, 30, 180, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 375, 500, 176);

        jButton5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton5.setText("Update Stock");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(190, 300, 110, 25);

        jButton7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton7.setText("Add To Stock");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(40, 300, 130, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creamstone/download.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 0, 102, 112);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creamstone/admin back.jpg"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(1002, 613));
        jLabel9.setMinimumSize(new java.awt.Dimension(1002, 613));
        jLabel9.setPreferredSize(new java.awt.Dimension(1002, 613));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1002, 610);

        jMenuBar1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(95, 32769));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(61, 21));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(95, 21));

        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Track");
        jMenu2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creamstone/graphic_register.jpg"))); // NOI18N
        jMenuItem3.setText("Track Daily Sales");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creamstone/graphic_register.jpg"))); // NOI18N
        jMenuItem2.setText(" Track Store Stock");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creamstone/star.JPG"))); // NOI18N
        jMenuItem1.setText("Review Feedbacks");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

while(model.getRowCount()>0)
{
    model.removeRow(0);
}
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");

Statement st = con.createStatement();

String q ="Select * from stock";

ResultSet rs= st.executeQuery(q);
while(rs.next())
{
    String c = rs.getString("code");
    String n = rs.getString("name");
    int qt = rs.getInt("qty");
    int p = rs.getInt("price");
   //Object o= new Object{c,n,qt,p};
    model.addRow(new Object[]{c,n,qt,p});
}
 

}catch(Exception z)
{
    JOptionPane.showMessageDialog(this,z.getMessage());

}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
new start().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
new Admin_Daily_sales().setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
String code = c1.getSelectedItem().toString();

while(model.getRowCount()>0)
{
    model.removeRow(0);
}
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");

Statement st = con.createStatement();

String q ="delete from stock where code = '"+code+"'";

 st.executeUpdate(q);

 JOptionPane.showMessageDialog(this,"Stock Removed");

}catch(Exception z)
{
    JOptionPane.showMessageDialog(this,z.getMessage());

}

try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");

Statement st = con.createStatement();

String q ="Select * from stock";

ResultSet rs= st.executeQuery(q);
while(rs.next())
{
    String c = rs.getString("code");
    String n = rs.getString("name");
    int qt = rs.getInt("qty");
    int p = rs.getInt("price");
   //Object o= new Object{c,n,qt,p};
    model.addRow(new Object[]{c,n,qt,p});
}
 

}catch(Exception z)
{
    JOptionPane.showMessageDialog(this,z.getMessage());

}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
new Admin_Daily_sales().setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
new admin_stock().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
MessageFormat header  = new MessageFormat("Daily Stock");
        MessageFormat footer = new MessageFormat("www.creamstone.com"+"          CreamStone,Jaipur");
        

                         
        try
        {
            
        jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
                

        }catch(Exception e)
        {
            
        }
        
         new admin_stock().setVisible(true);
         this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
int qty = Integer.parseInt(t2.getText());
String code = c1.getSelectedItem().toString();
while(model.getRowCount()>0)
{
    model.removeRow(0);
}
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");

Statement st = con.createStatement();

String q ="Update stock set qty=qty+'"+qty+"' where code = '"+code+"'";

 st.executeUpdate(q);

 JOptionPane.showMessageDialog(this,"Stock Updated");

}catch(Exception z)
{
    JOptionPane.showMessageDialog(this,z.getMessage());

}

try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");

Statement st = con.createStatement();

String q ="Select * from stock";

ResultSet rs= st.executeQuery(q);
while(rs.next())
{
    String c = rs.getString("code");
    String n = rs.getString("name");
    int qt = rs.getInt("qty");
    int p = rs.getInt("price");
   //Object o= new Object{c,n,qt,p};
    model.addRow(new Object[]{c,n,qt,p});
}
 

}catch(Exception z)
{
    JOptionPane.showMessageDialog(this,z.getMessage());

}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int row =jTable1.getSelectedRow();
        Object c=jTable1.getValueAt(row, 0).toString();
        c1.setSelectedItem(c);
        String n=jTable1.getValueAt(row, 1).toString();
        t1.setText(n);
        String p=jTable1.getValueAt(row, 3).toString();
        t3.setText(p);
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

String code = c2.getSelectedItem().toString();
int qty=0;
try
{
Class.forName("java.sql.Driver");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");

Statement st = con.createStatement();

String q ="Select qty from stock where code = '"+code+"'";

 ResultSet rs=st.executeQuery(q);
 while(rs.next())
 {
     qty=rs.getInt("qty");
 }
l1.setText("The Availability of Particular code is :"+qty);
}catch(Exception z)
{
    JOptionPane.showMessageDialog(this,z.getMessage());

}




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new admin_feeds().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
