
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yashmor
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
                setIconImage(new ImageIcon(getClass().getResource("icon.jpg")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        NAME = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        CODE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PRICE = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AMOUNT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoice = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        QUANTITY = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DISCOUNT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        GRAND = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bill,Creamstone Parlor,Jaipur");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 204, 204));
        setMaximumSize(new java.awt.Dimension(981, 733));
        setMinimumSize(new java.awt.Dimension(981, 733));
        setPreferredSize(new java.awt.Dimension(981, 733));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 80, 17);

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Select Item");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 80, 17);

        jComboBox1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select An Item", "Hot chocolate fudge", "Death By chocolate", "Creamy red velvet", "Devils Brownie", "french vanilla", "nutty crunch", "Fresh Strawberry", "Choco Fudge", "Rich Chocolate", "Caramel Nuts", "Brownie Delight", "Belgium Royal", "Vanilla", "Strawberry", "Kesar Pista", "Fruit Exotica", "Lichee Lake", "Fresh Fruit & Nuts", "Dry Fruit Delight", "Nuts Overload", "Arabian Nights", "Karamel Sutra", "Twisted Karamel", "Cofee Craze", "Kulfee Kraze", "Creamy Strawberry", "Chatpata Guava", "Kala Jamun", "Meetha Paan", "Nutzilla", "Ferrero Rocher", "Celebrating Sitafal", "A date with nut", "Fruit Overload", "Nutella Horlicks", "Choco Hazel", "Oreo Shot", "Willy Wonka", "Chocoholics", "Chocolava", "Nutella Brownie", "Brownie Break", "Tiramasu", "Chocolate Overdose" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(114, 172, 323, 23);

        NAME.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        getContentPane().add(NAME);
        NAME.setBounds(114, 131, 323, 23);

        jTable1.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Code", "MRP", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(51, 102, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 380, 940, 128);

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 90, 20);

        CODE.setEditable(false);
        CODE.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        CODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODEActionPerformed(evt);
            }
        });
        getContentPane().add(CODE);
        CODE.setBounds(114, 213, 323, 23);

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Price(in INR)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 300, 80, 17);

        PRICE.setEditable(false);
        PRICE.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        getContentPane().add(PRICE);
        PRICE.setBounds(114, 297, 323, 23);

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Discount(in %)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 620, 120, 23);

        AMOUNT.setEditable(false);
        AMOUNT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        AMOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMOUNTActionPerformed(evt);
            }
        });
        getContentPane().add(AMOUNT);
        AMOUNT.setBounds(240, 590, 182, 23);

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 340, 110, 25);

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Bill Form");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(127, 11, 116, 114);

        invoice.setEditable(false);
        invoice.setBackground(new java.awt.Color(255, 204, 204));
        invoice.setColumns(20);
        invoice.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        invoice.setForeground(new java.awt.Color(51, 51, 51));
        invoice.setLineWrap(true);
        invoice.setRows(5);
        invoice.setWrapStyleWord(true);
        invoice.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)), "Invoice", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Microsoft YaHei UI Light", 0, 18), new java.awt.Color(204, 0, 102))); // NOI18N
        invoice.setOpaque(false);
        jScrollPane2.setViewportView(invoice);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(580, 30, 358, 300);

        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(860, 520, 77, 25);

        jButton3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton3.setText("Remove item from cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(240, 520, 180, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creamstone/download.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(19, 11, 102, 114);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Privilage Customers", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei UI", 1, 12), new java.awt.Color(204, 204, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("<html>Are You A Registered Customer ?\nIf yes then Login and Avail 10% discount</html>");

        jButton4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(82, 82, 82)
                .addComponent(jButton4)
                .addGap(133, 133, 133))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(480, 570, 480, 110);

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("Code");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 220, 80, 17);

        QUANTITY.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        QUANTITY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QUANTITYActionPerformed(evt);
            }
        });
        getContentPane().add(QUANTITY);
        QUANTITY.setBounds(114, 248, 323, 23);

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Price(in INR)");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 590, 110, 23);

        DISCOUNT.setEditable(false);
        DISCOUNT.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        DISCOUNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISCOUNTActionPerformed(evt);
            }
        });
        getContentPane().add(DISCOUNT);
        DISCOUNT.setBounds(240, 620, 182, 23);

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Total price(in INR)");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 650, 140, 23);

        GRAND.setEditable(false);
        GRAND.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        GRAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRANDActionPerformed(evt);
            }
        });
        getContentPane().add(GRAND);
        GRAND.setBounds(240, 650, 182, 23);

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/creamstone/admin back.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 980, 710);

        jMenuBar1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(95, 32769));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(61, 21));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(95, 21));

        jMenu1.setText("Home");
        jMenu1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Store");
        jMenu2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
float total_price=(float) 0.0;
    private void AMOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMOUNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMOUNTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Item = jComboBox1.getSelectedItem().toString();
        String Code = CODE.getText();
        float mrp = Float.parseFloat(PRICE.getText());
        float quan = Float.parseFloat(QUANTITY.getText());
        float stock = (float)0.0;
        String query1 = "SELECT qty from stock where name = '"+Item+"'";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery(query1); //run your query

            while (resultSet.next()) //go through each row that your query returns
            {
                stock = resultSet.getInt("qty"); //get the element in column "item_code"

            }

            resultSet.close();
            statement.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
        if(stock>=quan)
        {
            float price = quan * mrp;
            total_price += price;

            Object[] row = {Item,Code,mrp,quan,price};

            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(row);
            AMOUNT.setText(""+total_price);
            DISCOUNT.setText("0%");
            GRAND.setText(""+total_price);
            
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root", "1234");
                Statement stmt = (Statement) con.createStatement();
                String query="UPDATE STOCK SET qty = qty-'"+quan+"' WHERE NAME = '"+Item+"'";
                stmt.executeUpdate(query);

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }
        }
        else
        JOptionPane.showMessageDialog(null,("THE REQUIRED QUANTITY IS OUT OF STOCK\nTHE AVAILABLE QUANTITY IS "+stock));

               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
                new start().setVisible(true);
                this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
                new store().setVisible(true);
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 float amount = Float.parseFloat(GRAND.getText());

 String Name=NAME.getText();
   
 try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root", "1234");
            Statement stmt = (Statement) con.createStatement();
            String query="Insert INTO bill Values('"+Name+"','"+amount+"',date(now()))";
            stmt.executeUpdate(query);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog (this, e.getMessage());
            
           
        }
      
         
         invoice.append("\n"+"Name : "+Name+"\n\n"+"Total Bill : "+amount+"\n\n"+"Thank You For Visiting,Come Again"+"\n\n"+"Creamstone,Jaipur");
        
         
         
        String disc=DISCOUNT.getText(); 
        MessageFormat header  = new MessageFormat("Invoice"+"                   Customer Name:"+Name);
        MessageFormat footer = new MessageFormat("Total Bill : "+amount+"       Discount Applied"+disc+"         Triton MAll outlet,Contact:+91 9854522251");
        

                         
        try
        {
            
        jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
                

        }catch(Exception e)
        {
            
        }
        
       
        JOptionPane.showMessageDialog(null,"Order Fulfilled,Sit and Enjoy");
         new feedback_form().setVisible(true);
         this.dispose();

         
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        new userlogin().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODEActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int row =jTable1.getSelectedRow();
        String Model=jTable1.getModel().getValueAt(row,0).toString();
        jComboBox1.setSelectedItem(""+Model);
        String Model1=jTable1.getModel().getValueAt(row,1).toString();
        CODE.setText(""+Model1);
        String Model2=jTable1.getModel().getValueAt(row,2).toString();
        PRICE.setText(""+Model2);
        String Model3=jTable1.getModel().getValueAt(row,3).toString();
        QUANTITY.setText(""+Model3);        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String Item = jComboBox1.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row =jTable1.getSelectedRow();
        model.removeRow(row);
        float mrp = Float.parseFloat(PRICE.getText());
        float quan = Float.parseFloat(QUANTITY.getText());
        float total = quan*mrp;
        total_price -= total;
        float tax = (float) (total_price*0.05);
        AMOUNT.setText(""+total_price);
        GRAND.setText(""+total_price);
        
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root", "1234");
            Statement stmt = (Statement) con.createStatement();
            String query="UPDATE STOCK SET QTY = QTY+'"+quan+"' WHERE NAME = '"+Item+"'";
            stmt.executeUpdate(query);

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog (this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
 String Item = jComboBox1.getSelectedItem().toString();

        String query = "SELECT * from STOCK where NAME = '"+Item+"'";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery(query); //run your query

            while (resultSet.next()) //go through each row that your query returns
            {
                String Name = resultSet.getString("CODE"); //get the element in column "item_code"
                CODE.setText(Name);
                int price = resultSet.getInt("price");
                PRICE.setText(""+price);
                QUANTITY.setText("");
            }

            resultSet.close();
            statement.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.exit(0);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String uname=JOptionPane.showInputDialog("Enter UserName");
String pwd=JOptionPane.showInputDialog("Enter Password");
String name="",password="";
float discount=0;
 discount=(float) (total_price*0.1);
 
        // Clear the existing table

       
        

        String query1 = "SELECT username,password FROM customer WHERE username ='"+uname+"' and password='"+pwd+"'";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/creamstone","root","1234");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query1);

            while (rs.next()) {
               name=rs.getString("username");
                password=rs.getString("password");
            }      
        }    
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.exit(0);
        }
        
       if(uname.equals("")&&pwd.equals(""))
       {
           JOptionPane.showMessageDialog(null,"kindly enter complete details");
       }
      else  if (uname.equals(name)&&pwd.equals(password))
        {
            float total=total_price-discount;
             DISCOUNT.setText(""+discount);
             GRAND.setText(""+total);
        }
       else
      {
          JOptionPane.showMessageDialog(null,"username did not match,Either register or enter corect details.");
      }
     
      
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DISCOUNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISCOUNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DISCOUNTActionPerformed

    private void GRANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GRANDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GRANDActionPerformed

    private void QUANTITYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QUANTITYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QUANTITYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AMOUNT;
    private javax.swing.JTextField CODE;
    private javax.swing.JTextField DISCOUNT;
    private javax.swing.JTextField GRAND;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PRICE;
    private javax.swing.JTextField QUANTITY;
    private javax.swing.JTextArea invoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
